name: Update IPTV Channels

on:
  workflow_dispatch:   # ðŸ‘ˆ manueller Button
  schedule:
    - cron: "0 3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install requests pyyaml

      - name: Generate playlists
        run: python scripts/generate_channels.py

      - name: Commit changes
        run: |
          git config user.name "iptv-bot"
          git config user.email "bot@users.noreply.github.com"
          git add channels.md channels.m3u
          git commit -m "Update IPTV channels" || exit 0
          git push
